### PR TITLE
eel-gnome-extensions.c: Support whitespace in execution commands

### LINKED ISSUE #2571: Links to executables do not run, where the link contains a space - and this affects xfce4-terminal even after applying the gsettings workaround
```
 * Nemo version (nemo --version) 4.6.5
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used: not relevant
 * 32 or 64 bit: 64
 ```

**Issue**

[EDITED.]

When I use Nemo to run-in-terminal a script that has a space in its leafname, an error box appears, saying , ' No such file or directory'.

**Steps to reproduce**

[Edited for: easier reproducibility; clarity; and to ensure that the error message that I give is the one that appears on the latest version - well, version 5.6.4 - of nemo.]

1. Have a executable bash script `~/testy McTesty`
2. . Use Nemo to make a link to it. (The link can be left where it is created, which can be in `~`.)
3. Run the link via Nemo, with Nemo set to ask what to do when running executables - choose 'run in terminal' when asked.
4. See error window that says: 'Failed to execute child process "/home/<myUser>/testy": Failed to execve [_sic_]: No such file or directory.'

**Expected behaviour**

The executable should run.

**Other information**

- I have the problem using both Gnome terminal and xfce4-terminal.
- File manager PcManFm does not have the problem - it runs the executable.
- **I tried the gsetting workaround (`gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg -- `) recommended in #2499) and that makes things work for Gnome-terminal _but not for the xfce terminal_.**
- I open this the present issue at the request of icarter09.

### PR DESCRIPTION
**Pull request by rcalixte**
A default command line with whitespace will fail to execute, either silently or with a visible error, depending on the trigger. In addition, some actions would default to launching with GNOME Terminal even when another terminal was configured as the default. This adds a default list of terminals, proper switches for execution, and a boolean for whether or not the command line sequence needs to be escaped.

Closes #2571

### CODE REVIEW

File: eel/eel-gnome-extensions.c [hunk 1]
```diff
@@ -33,78 +33,92 @@
...
     if (terminal != NULL) {
-        gchar *term_path = NULL;
-
-        term_path = g_find_program_in_path (terminal);
-
-        if (term_path != NULL) {
-            gchar *exec_flag = NULL;
+        for (i = 0; i < G_N_ELEMENTS (known_terminals); i++) {
+            if (g_strcmp0 (known_terminals[i].exec, terminal) == 0) {
+                prefix = g_string_new (g_strdup_printf ("%s %s", known_terminals[i].exec, known_terminals[i].exec_arg));
```
Comment (mtwebster) [inline eel/eel-gnome-extensions.c:81]: This should be `g_string_new_take`, since `g_strdup_printf` returns a new string.

```
==928358== 
==928358== 36 bytes in 2 blocks are definitely lost in loss record 14,270 of 37,292
==928358==    at 0x4846828: malloc (vg_replace_malloc.c:442)
==928358==    by 0x5B97937: __vasprintf_internal (vasprintf.c:116)
==928358==    by 0x56A0A32: UnknownInlinedFun (stdio2.h:169)
==928358==    by 0x56A0A32: g_vasprintf (gprintf.c:341)
==928358==    by 0x56715E4: g_strdup_vprintf (gstrfuncs.c:511)
==928358==    by 0x5671940: g_strdup_printf (gstrfuncs.c:541)
==928358==    by 0x234D26: UnknownInlinedFun (eel-gnome-extensions.c:81)
==928358==    by 0x234D26: eel_gnome_open_terminal_on_screen (eel-gnome-extensions.c:138)
==928358==    by 0x217C12: UnknownInlinedFun (nemo-program-choosing.c:201)
==928358==    by 0x217C12: nemo_launch_application_from_command (nemo-program-choosing.c:255)
==928358==    by 0x179AD7: UnknownInlinedFun (nemo-mime-actions.c:1655)
==928358==    by 0x179AD7: activate_callback.lto_priv.0 (nemo-mime-actions.c:1944)
==928358==    by 0x1FAC31: UnknownInlinedFun (nemo-file.c:8764)
==928358==    by 0x1FAC31: file_list_file_ready_callback (nemo-file.c:8754)
```

File: eel/eel-gnome-extensions.c [hunk 2]
```diff
@@ -33,78 +33,92 @@
...
+        gchar *term_path = NULL;
 
-            if (exec_flag == NULL) {
-                prefix = g_strdup (term_path);
-            } else {
-                prefix = g_strdup_printf ("%s %s", term_path, exec_flag);
+        for (i = 0; i < G_N_ELEMENTS (known_terminals); i++) {
+            term_path = g_find_program_in_path (known_terminals[i].exec);
+            if (term_path != NULL) {
+                prefix = g_string_new (g_strdup_printf ("%s %s", known_terminals[i].exec, known_terminals[i].exec_arg));
```
Comment (mtwebster) [inline eel/eel-gnome-extensions.c:93]: same

**Comment by mtwebster** [comment]
I notice we never free `command_line` in `eel_gnome_open_terminal_on_screen`, can you add also?
```diff
@@ -155,4 +155,6 @@ eel_gnome_open_terminal_on_screen (const gchar *command,
 
                g_error_free (error);
        }
+
+    g_free (command_line);
 }
```
